version: '3.8'

services:
  db:
    container_name: videoclub-psql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    image: postgres:alpine
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgres/data

  adminer:
    container_name: videoclub-adminer
    image: adminer
    ports:
      - '8080:8080'

volumes:
  postgres-data:
