version: '3.8'

services:
  api:
    container_name: videoclub-api
    build: .
    command: 'uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    ports:
      - 8000:8000
    volumes:
      - ./:/home/app/fastapi
