version: '3.8'

services:
  db:
    container_name: videoclub-psql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - 5432
    image: postgres:alpine
    volumes:
      - ./postgres-data:/var/lib/postgres/data

  adminer:
    container_name: videoclub-adminer
    image: adminer
    ports:
      - '8080:8080'

  api:
    build:
      context: ./project
      dockerfile: Dockerfile
    command: |
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    container_name: videoclub-api
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - ./project:/home/app/fastapi

volumes:
  postgres-data:
